[package]
name = "chat-client"
version = "0.1.0"
edition = "2024"

[dependencies]
chat-client-lib = { path = "../chat-client-lib" }
tokio = { version = "1.36", features = ["full"] }
anyhow = "1.0"
clap = { version = "4.4", features = ["derive", "env"] }